# Generated by Django 5.1.3 on 2025-10-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoadSpecsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
